# Generated by Django 5.0.6 on 2024-07-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
