# Generated by Django 5.0.6 on 2024-08-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
