# Generated by Django 5.0.6 on 2024-08-10 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
